name: Deploy project

on:
  workflow_run:
    workflows: ['Build project']
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Pull DB docker image
      run: sudo docker pull forelock/master-work-db
    - name: Delete old DB docker container
      run: sudo docker rm -f master-work-db-container || true
    - name: Run DB docker container
      run: sudo docker run -d -p 5432:5432 -name master-work-db-container -v /home/ubuntu/master-work-app/db/data:/var/lib/postgresql/data forelock/master-work-db
