# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Step 1: Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out the repository
        uses: actions/checkout@v4
  
      # Step 2: Run docker compose
      - name: Docker Compose Action
        uses: hoverkraft-tech/compose-action@v2.0.2
        with:
          # Description: Path to compose file(s). It can be a list of files. It can be
          # absolute or relative to the current working directory (cwd).
          #
          # Default: ./docker-compose.yml
          compose-file: "./app-project/docker-compose.yaml"
