name: Sequential tests

on:
#  push:
#    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
      DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
    steps:
    - uses: actions/checkout@v4
    - name: Cache Docker layers
      uses: actions/cache@v4
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-docker-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-docker-
    - name: Login Dockerhub
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - name: Build DB Docker image
      run: docker build ./app-project --file ./app-project/db/Dockerfile --tag forelock/master-work-db:latest
    - name: Build App Docker image
      run: docker build ./app-project --file ./app-project/tomcat/Dockerfile --tag forelock/master-work-app:latest
    - name: Push DB image to Dockerhub  
      run: docker push forelock/master-work-db:latest
    - name: Push App image to Dockerhub  
      run: docker push forelock/master-work-app:latest

  deployTesting:
    name: Deploy Testing Env
    needs: build
    runs-on: self-hosted
    steps:
    - name: Clean up Docker to free up space
      run: sudo docker system prune -af
    - name: Ensure Docker network created
      run: |
        if [ ! "$(sudo docker network ls --filter name=^local$ --format='{{.Name}}')" ]; then
          echo "Creating Docker network 'local'..."
          sudo docker network create --driver bridge local
        else
          echo "Docker network 'local' already exists."
        fi
    - name: Run new DB docker container
      run: |
        sudo docker pull forelock/master-work-db
        sudo docker rm -f master-work-db-container || true
        sudo docker run -d --restart always -p 5432:5432 --name master-work-db-container --network local -v /home/ubuntu/master-work-app/db/data:/var/lib/postgresql/data forelock/master-work-db
    - name: Run Adminer docker container
      run: |
        # Check if the container exists
        if [ "$(sudo docker ps -q -f name=master-work-adminer-container)" ]; then
          echo "Container 'master-work-adminer-container' is already running."
        else
          # Check if the container exists but is stopped, and start it
          if [ "$(sudo docker ps -aq -f name=master-work-adminer-container)" ]; then
            echo "Deleting existing container 'master-work-adminer-container'..."
            sudo docker delete master-work-adminer-container
          fi
          # If the container does not exist, create and start it
          echo "Creating and starting new container 'master-work-adminer-container'..."
          sudo docker run -d --restart always -p 8081:8080 --name master-work-adminer-container --network local adminer:4.8.1
        fi
    - name: Run new App docker container
      run: |
        sudo docker pull forelock/master-work-app
        sudo docker rm -f master-work-app-container || true
        sudo docker run -d --restart always -p 8080:8080 -p 5005:5005 --name master-work-app-container --network local forelock/master-work-app

  playwright-tests:
    name: Playwright Tests
    needs: deployTesting
    timeout-minutes: 10
    runs-on: ubuntu-latest
    env:
      HOST: ${{secrets.TEST_HOST}}
      USERNAME: ${{secrets.ADMIN_USERNAME}}
      PASSWORD: ${{secrets.ADMIN_PASSWORD}}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
        working-directory: playwright-project
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        working-directory: playwright-project
      - name: Playwright test run
        run: npx playwright test
        working-directory: playwright-project
      - name: Publish summary CTRF report with
        run: npx github-actions-ctrf ctrf-report.json
        working-directory: playwright-project/reports/
        if: always()
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-project/reports/
          retention-days: 30

  selenium-tests:
    name: Selenium Tests
    needs: playwright-tests
    timeout-minutes: 10
    runs-on: ubuntu-latest
    env:
      HOST: ${{secrets.TEST_HOST}}
      USERNAME: ${{secrets.ADMIN_USERNAME}}
      PASSWORD: ${{secrets.ADMIN_PASSWORD}}
      IS_HEADLESS: true
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Selenium test run
        run: mvn clean test -DsuiteXmlFile=src/test/resources/testng.xml
        working-directory: selenium-project
      - name: Publish summary CTRF report with
        run: npx github-actions-ctrf ctrf-report.json
        working-directory: selenium-project/target/
        if: always()

  cypress-tests:
    name: Cypress Tests
    needs: selenium-tests
    timeout-minutes: 10
    runs-on: ubuntu-latest
    env:
      CYPRESS_BASE_URL: ${{secrets.TEST_BASE_URL}}
      CYPRESS_USERNAME: ${{secrets.ADMIN_USERNAME}}
      CYPRESS_PASSWORD: ${{secrets.ADMIN_PASSWORD}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress test run
        uses: cypress-io/github-action@v6
        with:
          start: npm start
          browser: chrome
          publish-summary: false
          working-directory: cypress-project
      - name: Publish summary CTRF report with
        run: npx github-actions-ctrf ctrf-report.json
        working-directory: cypress-project/reports/
        if: always()