name: Sequential tests

on:
#  push:
#    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  playwright-tests2:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    env:
      BASE_URL: ${{secrets.TEST_BASE_URL}}
      USERNAME: ${{secrets.ADMIN_USERNAME}}
      PASSWORD: ${{secrets.ADMIN_PASSWORD}}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
        working-directory: playwright-project
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        working-directory: playwright-project
      - name: Playwright test run
        run: npx playwright test
        working-directory: playwright-project
      - name: Publish summary CTRF report with
        run: npx github-actions-ctrf ctrf-report.json
        working-directory: playwright-project/reports/
        if: always()
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-project/reports/
          retention-days: 30

  selenium-tests2:
    needs: playwright-tests2
    timeout-minutes: 10
    runs-on: ubuntu-latest
    env:
      BASE_URL: ${{secrets.TEST_BASE_URL}}
      USERNAME: ${{secrets.ADMIN_USERNAME}}
      PASSWORD: ${{secrets.ADMIN_PASSWORD}}
      IS_HEADLESS: true
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Selenium test run
        run: mvn clean test -DsuiteXmlFile=src/test/resources/testng2.xml
        working-directory: selenium-project
      - name: Publish summary CTRF report with
        run: npx github-actions-ctrf ctrf-report.json
        working-directory: selenium-project/target/
        if: always()

  cypress-tests2:
    needs: selenium-tests2
    timeout-minutes: 10
    runs-on: ubuntu-latest
    env:
      CYPRESS_BASE_URL: ${{secrets.TEST_BASE_URL}}
      CYPRESS_USERNAME: ${{secrets.ADMIN_USERNAME}}
      CYPRESS_PASSWORD: ${{secrets.ADMIN_PASSWORD}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress test run
        uses: cypress-io/github-action@v6
        with:
          start: npm start
          browser: chrome
          publish-summary: false
          working-directory: cypress-project
      - name: Publish summary CTRF report with
        run: npx github-actions-ctrf ctrf-report.json
        working-directory: cypress-project/reports/
        if: always()